/******************************************************************************
Finite State Machine
Project: cncpp
Description: CNC

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.1
Generation date: 2025-05-15 12:18:38 +0200
Generated from: src/fsm.dot
The finite state machine has:
  8 states
  7 transition functions

******************************************************************************/

#include "fsm.hpp"
    
using namespace std;
    

// SEARCH FOR Your Code Here FOR CODE INSERTION POINTS!

// struct FSMData{
// 
//   cncpp::Machine machine;
//   cncpp::Program program;
//   data_t t_tot = 0, t_blk = 0;
// 
//   FSMData(string machine_file) : machine(machine_file), program(&machine) {}

// }

namespace cncpp {

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */                                             

// Function to be executed in state STATE_INIT
// valid return states: STATE_IDLE, STATE_STOP
template<class T> 
state_t do_init(T &data) {
  state_t next_state = cncpp::STATE_IDLE;
  
  // STEPS

  // step 1 -> connnect machine via MQTT
  data.machine.connect();

  // step 2 -> set machine to zero
  data.machine.position(data.machine.zero());
  data.machine.setpoint(data.machine.zero());

  // step 3 -> message the user
  cerr << fg::green << "Connected to machine" << style::bold << data.machine.mqtt_host() << style::reset << fg::reset << endl;


  
  return next_state;
}

// Function to be executed in state STATE_IDLE
// valid return states: NO_CHANGE, STATE_IDLE, STATE_LOAD_BLOCK, STATE_STOP, STATE_GO_TO_ZERO
// SIGINT triggers an emergency transition to STATE_STOP
template<class T> 
state_t do_idle(T &data) {
  state_t next_state = cncpp::NO_CHANGE;

  // STEPS

  // step 1 -> wait for user input -> user instructions
  cerr << "Press " << fg::green << "<space>" << fg::reset << " to run, " << fg::blue << "z" << fg::reset << " to go to zero, " << fg::red << "q" << fg::reset << " to quit" << endl;

  // step 2 -> select next state according to keypress
  char key = keystrocker::read_key();
  switch(key){

    case ' ': 
      next_state = STATE_LOAD_BLOCK;
      data.program.rewind();          // we call the execution from zero
      break;

    case 'q':
    case 'Q':
      next_state = STATE_STOP;
      break;

    case 'z':
    case 'Z':
      next_state = STATE_GO_TO_ZERO;
      break;

    default:
      break;

  }

  // we need to store the block time and the total time
  // step 3 -> reset time
  data.t_tot = data.t_blk = 0.0;

  // step 4 -> synch
  data.machine.sync();

  return next_state;
}

// Function to be executed in state STATE_STOP
// valid return states: NO_CHANGE
template<class T> 
state_t do_stop(T &data) {
  state_t next_state = cncpp::NO_CHANGE;

  // STEPS

  // step 1 -> disable the signal handler
  signal(SIGINT, SIG_DFL);

  // step 2 -> disconnect
  data.machine.listen_stop();

  // step 3 -> message the user
  cerr << fg::red << style::bold << "STOP! " << fg::reset << style::reset << endl;
  
  return next_state;
}

// Function to be executed in state STATE_LOAD_BLOCK
// valid return states: STATE_IDLE, STATE_NO_MOTION, STATE_RAPID_MOTION, STATE_INTERP_MOTION
template<class T> 
state_t do_load_block(T &data) {
  state_t next_state = cncpp::STATE_RAPID_MOTION;

  // STEPS 

  // step 1 -> load the next block and go back to idle if it is the last one
  data.program.load_next();

  if(data.program.done()){
    return STATE_IDLE;
  }  

  // step 2 -> check block type
  auto &b = data.program.current();
  cerr << "Loading " << b.desc() << endl;
  switch(b.type()){

    case Block::BlockType::NO_MOTION:
      next_state = STATE_NO_MOTION;
      break;
    
    case Block::BlockType::RAPID_MOTION:
      next_state = STATE_RAPID_MOTION;
      break:

    case Block::BlockType::LINE:
    case Block::BlockType::CWA:
    case Block::BlockType::CCWA:
      next_state = STATE_INTERP_MOTION;
      break;

    default:
      next_state = STATE_IDLE;
      break;
  }

  data.t_tot += data.machine.tq();

  return next_state;
}

// Function to be executed in state STATE_GO_TO_ZERO
// valid return states: NO_CHANGE, STATE_IDLE, STATE_GO_TO_ZERO
// SIGINT triggers an emergency transition to STATE_STOP
template<class T> 
state_t do_go_to_zero(T &data) {
  state_t next_state = cncpp::NO_CHANGE;

  // STEPS

  // step 1 -> synch machine setpoint
  data.machine.sync(true);

  // step 2 -> check if zero has been reached
  if(data.machine.error() < data.machine.max_error()){
    next_state = STATE_IDLE;
  }

  // step 3 -> check for ctrl-c
  if(stop_requested){
    stop_requested = false;       // reset the flag
    next_state = STATE_IDLE;
  }

  return next_state;
}

// Function to be executed in state STATE_NO_MOTION
// valid return states: STATE_LOAD_BLOCK
template<class T> 
state_t do_no_motion(T &data) {
  state_t next_state = cncpp::STATE_LOAD_BLOCK;
  
  // STEPS
  // step 1 -> print that we are not moving

  cerr << fg::yellow << "No motion block: " << fg::reset << data.program.current() -> desc() << endl;

  // step 2 -> increment timers
  data.t_tot += data.machine.tq();
  
  return next_state;
}

// Function to be executed in state STATE_RAPID_MOTION
// valid return states: NO_CHANGE, STATE_LOAD_BLOCK, STATE_RAPID_MOTION
// SIGINT triggers an emergency transition to STATE_STOP
template<class T> 
state_t do_rapid_motion(T &data) {
  state_t next_state = cncpp::NO_CHANGE;

  // STEPS 
  // step 1 -> synch the machine

  // step 2 -> exit if error is small or max time has elapsed

  // step 3 -> exit for ctrl-c

  // step 4 -> get current position and print out values table

  // step 5 -> increment timers


  return next_state;
}

// Function to be executed in state STATE_INTERP_MOTION
// valid return states: NO_CHANGE, STATE_LOAD_BLOCK, STATE_INTERP_MOTION
// SIGINT triggers an emergency transition to STATE_STOP
template<class T> 
state_t do_interp_motion(T &data) {
  state_t next_state = cncpp::UNIMPLEMENTED;
  /* Your Code Here */
  
  return next_state;
}


/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */                                              

// This function is called in 1 transition:
// 1. from idle to load_block
template<class T>
void reset(T &data) {
  /* Your Code Here */
}

// This function is called in 1 transition:
// 1. from idle to go_to_zero
template<class T>
void begin_zero(T &data) {
  /* Your Code Here */
}

// This function is called in 1 transition:
// 1. from load_block to rapid_motion
template<class T>
void begin_rapid(T &data) {
  /* Your Code Here */
}

// This function is called in 1 transition:
// 1. from load_block to interp_motion
template<class T>
void begin_interp(T &data) {
  /* Your Code Here */
}

// This function is called in 1 transition:
// 1. from rapid_motion to load_block
template<class T>
void end_rapid(T &data) {
  /* Your Code Here */
}

// This function is called in 1 transition:
// 1. from interp_motion to load_block
template<class T>
void end_interp(T &data) {
  /* Your Code Here */
}

// This function is called in 1 transition:
// 1. from go_to_zero to idle
template<class T>
void end_zero(T &data) {
  /* Your Code Here */
}


}; // namespace cncpp


// Example usage:
#ifdef TEST_MAIN
#include <unistd.h>
#include <thread>

struct Data {
  int count;
};

int main() {
  Data data = {1};
  auto fsm = cncpp::FiniteStateMachine(&data);
  fsm.set_timing_function([]() {
    std::this_thread::sleep_for(std::chrono::seconds(1));
  });
  fsm.run([&](Data &s) {
    std::cout << "State: " << fsm.state() << " data: " << s.count << std::endl;
  });
  return 0;
}
#endif // TEST_MAIN
