/******************************************************************************
Finite State Machine
Project: cncpp
Description: CNC

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.2
Generation date: 2025-05-28 11:44:06 +0200
Generated from: src/fsm.dot
The finite state machine has:
  8 states
  7 transition functions


TODO -> rewrite here all what we wrote in fsm.cpp, so we won't include the definitions file in the main script code

******************************************************************************/

    
#include "cncpp.hpp"
#include <keystroker.h>
#include <rang.hpp>
#include <fmt/core.h>
    
using namespace std;
using namespace rang;
using namespace fmt;

// SEARCH FOR Your Code Here FOR CODE INSERTION POINTS!


namespace cncpp {

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */                                             

// Function to be executed in state STATE_INIT
// valid return states: STATE_IDLE, STATE_STOP
template<class T> 
state_t do_init(T &data) {
  state_t next_state = cncpp::STATE_IDLE;
  
  // STEPS

  // step 1 -> connnect machine via MQTT
  data.machine.connect();

  // step 2 -> set machine to zero
  data.machine.position(data.machine.zero());
  data.machine.setpoint(data.machine.zero());

  // step 3 -> message the user
  cerr << fg::green << "Connected to machine" << style::bold << data.machine.mqtt_host() << style::reset << fg::reset << endl;
  
  return next_state;
}

// Function to be executed in state STATE_IDLE
// valid return states: NO_CHANGE, STATE_IDLE, STATE_LOAD_BLOCK, STATE_STOP, STATE_GO_TO_ZERO
// SIGINT triggers an emergency transition to STATE_STOP
template<class T> 
state_t do_idle(T &data) {
  state_t next_state = cncpp::NO_CHANGE;

  // STEPS

  // step 1 -> wait for user input -> user instructions
  cerr << "Press " << fg::green << "<space>" << fg::reset << " to run, " << fg::blue << "z" << fg::reset << " to go to zero, " << fg::red << "q" << fg::reset << " to quit" << endl;

  // step 2 -> select next state according to keypress
  char key = keystroker::read_key();
  switch(key){

    case ' ': 
      next_state = STATE_LOAD_BLOCK;
      data.program.rewind();          // we call the execution from zero
      break;

    case 'q':
    case 'Q':
      next_state = STATE_STOP;
      break;

    case 'z':
    case 'Z':
      next_state = STATE_GO_TO_ZERO;
      break;

    default:
      break;

  }

  // we need to store the block time and the total time
  // step 3 -> reset time
  data.t_tot = data.t_blk = 0.0;

  // step 4 -> synch
  // data.machine.sync(false);
  data.machine.loop();
  return next_state;
}

// Function to be executed in state STATE_STOP
// valid return states: NO_CHANGE
template<class T> 
state_t do_stop(T &data) {
  state_t next_state = cncpp::NO_CHANGE;

  // STEPS

  // step 1 -> disable the signal handler
  signal(SIGINT, SIG_DFL);

  // step 2 -> disconnect
  data.machine.sync(false);
  data.machine.listen_stop();

  // step 3 -> message the user
  cerr << fg::red << style::bold << "STOP! " << fg::reset << style::reset << endl;
  
  return next_state;
}

// Function to be executed in state STATE_LOAD_BLOCK
// valid return states: STATE_IDLE, STATE_NO_MOTION, STATE_RAPID_MOTION, STATE_INTERP_MOTION
template<class T> 
state_t do_load_block(T &data) {
  state_t next_state = cncpp::STATE_RAPID_MOTION;

  // STEPS 

  // step 1 -> load the next block and go back to idle if it is the last one
  data.program.load_next();

  if(data.program.done()){
    return STATE_IDLE;
  }  

  // step 2 -> check block type
  auto &b = *data.program.current();
  cerr << "Loading " << b -> desc() << endl;
  switch(b -> type()){

    case Block::BlockType::NO_MOTION:
      next_state = STATE_NO_MOTION;
      break;
    
    case Block::BlockType::RAPID:
      next_state = STATE_RAPID_MOTION;
      break;

    case Block::BlockType::LINE:
    case Block::BlockType::CWA:
    case Block::BlockType::CCWA:
      next_state = STATE_INTERP_MOTION;
      break;

    default:
      next_state = STATE_IDLE;
      break;
  }

  data.t_tot += data.machine.tq();

  return next_state;
}

// Function to be executed in state STATE_GO_TO_ZERO
// valid return states: NO_CHANGE, STATE_IDLE, STATE_GO_TO_ZERO
// SIGINT triggers an emergency transition to STATE_STOP
template<class T> 
state_t do_go_to_zero(T &data) {
  state_t next_state = cncpp::NO_CHANGE;
  data_t distance = INFINITY;
  auto &m = data.machine;
  // STEPS

  // step 1 -> synch machine setpoint
  data.machine.sync(true);

  if (m.position().is_complete()) {
    // Don't rely on error, for it is calculated ex-post, so we might get the
    // error at the end of previous loop (ie too small)
    distance = m.setpoint().delta(m.position()).length();
  }
  cerr << "Position: " << m.position().desc()
      << " Distance: " << style::bold << distance << style::reset << endl;
  
  // 2. check if zero has been reached
  if (m.position().is_complete() && distance < m.max_error()) {
    next_state = STATE_IDLE;
  }

  // step 3 -> check for ctrl-c
  if(stop_requested){
    stop_requested = false;       // reset the flag
    next_state = STATE_IDLE;
  }

  return next_state;
}

// Function to be executed in state STATE_NO_MOTION
// valid return states: STATE_LOAD_BLOCK
template<class T> 
state_t do_no_motion(T &data) {
  state_t next_state = cncpp::STATE_LOAD_BLOCK;
  
  // STEPS
  // step 1 -> print that we are not moving

  cerr << fg::yellow << "No motion block: " << fg::reset << (*data.program.current()) -> desc() << endl;

  // step 2 -> increment timers
  data.t_tot += data.machine.tq();
  
  return next_state;
}

// Function to be executed in state STATE_RAPID_MOTION
// valid return states: NO_CHANGE, STATE_LOAD_BLOCK, STATE_RAPID_MOTION
// SIGINT triggers an emergency transition to STATE_STOP
template<class T> 
state_t do_rapid_motion(T &data) {
  state_t next_state = cncpp::NO_CHANGE;

  data_t duration;
  Block &b = **data.program.current();

  try{
    // STEPS 
    // step 1 -> synch the machine
    data.machine.sync(true);

    // step 2 -> exit if error is small or max time has elapsed
    duration = b.length() / data.machine.fmax() * 60.0 * 2;
    if(data.machine.error() < data.machine.max_error() || data.t_blk > duration){

      cerr << "Rapid block " << b.desc() << " completed." << endl;
      cerr << "Duration: " << duration << " s" << endl;
      cerr << "Elapsed time: " << data.t_blk << " s" << endl;
      cerr << "Error: " << data.machine.error() << " mm" << endl;
      next_state = cncpp::STATE_LOAD_BLOCK;
    }

    // step 3 -> exit for ctrl-c
    if(stop_requested){

      cerr << "Rapid block " << b.desc() << " skipped" << endl;
      stop_requested = false;
      next_state = cncpp::STATE_LOAD_BLOCK;
    }

    // step 4 -> get current position and print out values table
    Point p = data.machine.position();
    Point tgt = b.target();
    data_t lambda = min(data.machine.error() / b.length(), 1.0);

    cout << fmt::format("{:0>3d} {:0>2d} {:.3f} {:.3f} {:.3f} {:.3f} {:.1f} {:.3f} {:.3f} {:.3f} {:.3f} {:.3f} {:.3f} {:.3f}", b.n(), static_cast<int>(b.type()), data.t_tot, data.t_blk, lambda, lambda * b.length(), data.machine.fmax(), b.profile().current_acc, tgt.x(), tgt.y(), tgt.z(), p.x(), p.y(), p.z()) << endl;

  } catch (const bad_optional_access &e){
    cerr << fg::yellow << "Waiting for machine position" << fg::reset << endl;
  }
  // step 5 -> increment timers
  data.t_tot += data.machine.tq();
  data.t_blk += data.machine.tq();

  return next_state;
}

// Function to be executed in state STATE_INTERP_MOTION
// valid return states: NO_CHANGE, STATE_LOAD_BLOCK, STATE_INTERP_MOTION
// SIGINT triggers an emergency transition to STATE_STOP
template<class T> 
state_t do_interp_motion(T &data) {
  state_t next_state = cncpp::NO_CHANGE;
  /* Your Code Here */

  Block &b = **data.program.current();
  data_t lambda, speed;
  data_t tq = data.machine.tq();

  // STEPS 
  // step 1 -> interpolate motion
  Point p = data.machine.position();
  Point tgt = b.interpolate(data.t_blk, lambda, speed);

  // step 2 -> print values table
  try{
    cout << fmt::format("{:0>3d} {:0>2d} {:.3f} {:.3f} {:.3f} {:.3f} {:.1f} {:.3f} {:.3f} {:.3f} {:.3f} {:.3f} {:.3f} {:.3f}", b.n(), static_cast<int>(b.type()), data.t_tot, data.t_blk, lambda, lambda * b.length(), speed, b.profile().current_acc, tgt.x(), tgt.y(), tgt.z(), p.x(), p.y(), p.z()) << endl;
  
  } catch(const bad_optional_access &e){
    cout << fmt::format("{:0>3d} {:0>2d} {:.3f} {:.3f} {:.3f} {:.3f} {:.1f} {:.3f} {:.3f} {:.3f} {:.3f} {:>3} {:>3} {:>3}", b.n(), static_cast<int>(b.type()), data.t_tot, data.t_blk, lambda, lambda * b.length(), speed, b.profile().current_acc, tgt.x(), tgt.y(), tgt.z(), "-", "-", "-") << endl;  
  }

  // step 3 -> sync the machine
  data.machine.setpoint(tgt);
  data.machine.sync(false);

  // step 4 -> check if it's done
  if(data.t_blk > b.dt() + tq / 10){
    next_state = cncpp::STATE_LOAD_BLOCK;
  }

  // step 5 -> increment times
  data.t_tot += tq;
  data.t_blk += tq;
  
  return next_state;
}


/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */                                              
// This function is called in 1 transition:
// 1. from idle to load_block
template<class T>
void reset(T &data) {

  data.t_tot = data.t_blk = 0.0;
  cout << "n type, t_tot t_blk lambda s feedrate acc xr yr zr x y z" << endl;  
}

// This function is called in 1 transition:
// 1. from idle to go_to_zero
template<class T>
void begin_zero(T &data) {
  
  data.machine.listen_start();
  data.machine.setpoint(data.machine.zero());
  data.machine.sync(true);
  cerr << "Going to zero at " << data.machine.zero().desc() << endl;
}

// This function is called in 1 transition:
// 1. from load_block to rapid_motion
template<class T>
void begin_rapid(T &data) {


  Block &b = **data.program.current();
  data.t_blk = 0.0;
  data.machine.listen_start();
  data.machine.setpoint(b.target());
  data.machine.sync(true);
}

// This function is called in 1 transition:
// 1. from load_block to interp_motion
template<class T>
void begin_interp(T &data) {

  data.machine.sync(false);
  data.t_blk = 0.0;
}

// This function is called in 1 transition:
// 1. from rapid_motion to load_block
template<class T>
void end_rapid(T &data) {

  data.machine.listen_stop();
  data.machine.sync(false);
}

// This function is called in 1 transition:
// 1. from interp_motion to load_block
template<class T>
void end_interp(T &data) {

  data.machine.sync(false);
}

// This function is called in 1 transition:
// 1. from go_to_zero to idle
template<class T>
void end_zero(T &data) {

  data.machine.listen_stop();
  data.machine.sync(false);
}


}; // namespace cncpp


// Example usage:
#ifdef TEST_MAIN
#include <unistd.h>
#include <thread>

struct Data {
  int count;
};

int main() {
  Data data = {1};
  auto fsm = cncpp::FiniteStateMachine(&data);
  fsm.set_timing_function([]() {
    std::this_thread::sleep_for(std::chrono::seconds(1));
  });
  fsm.run([&](Data &s) {
    std::cout << "State: " << fsm.state() << " data: " << s.count << std::endl;
  });
  return 0;
}
#endif // TEST_MAIN
